RSI_info <- list(
  list(
    header = "Purpose:",
    bullets = c("The RSI helps traders assess whether an asset is overbought or oversold, which can indicate potential reversal points or continuation of trends."),
    subpoints = NULL
  ),
  list(
    header = "Overbought and Oversold Levels:",
    bullets = c("The RSI ranges from 0 to 100, with levels typically set at 70 (overbought) and 30 (oversold)."),
    subpoints = list(
      list(name = "Overbought:", content = "An RSI above 70 may indicate that the asset is overbought, suggesting a potential price correction or reversal."),
      list(name = "Oversold:", content = "An RSI below 30 may indicate that the asset is oversold, suggesting a potential buying opportunity.")
    )
  ),
  list(
    header = "Divergence:",
    bullets = c("Divergence between the RSI and the price can indicate potential reversals.",
                "If prices are making new highs while the RSI is making lower highs, it may signal weakening momentum and a possible reversal."),
    subpoints = NULL
  ),
  list(
    header = "Trend Strength:",
    bullets = c("An RSI consistently above 50 indicates that the average gains are higher than the average losses, suggesting a bullish trend.",
                "An RSI consistently below 50 indicates that the average losses are greater than the average gains, suggesting a bearish trend."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "Being based on past price movements, RSI can lag behind current market trends, which may lead to missed trading opportunities."),
      list(name = "False Signals:", content = "RSI can produce false signals, particularly in strong trending markets. A security can remain overbought or oversold for extended periods, leading traders to prematurely enter or exit positions.")
    )
  )
)

SAR_info <- list(
  list(
    header = "Purpose:",
    bullets = c("The SAR indicator provides potential stop-loss levels and helps traders identify whether an asset is in an uptrend or downtrend.",
                "It can signal potential entries and exits based on its position relative to the price."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("The calculation incorporates an acceleration factor, which increases as the trend continues.",
                "This allows the SAR to follow the price more closely in strong trends.",
                "The SAR is calculated based on the price movements of an asset. It is plotted as dots either above or below the price line:"),
    subpoints = list(
      list(name = "When the SAR is below the price, it indicates an uptrend.", content = ""),
      list(name = "When the SAR is above the price, it indicates a downtrend.", content = "")
    )
  ),
  list(
    header = "Trend Direction:",
    bullets = NULL,
    subpoints = list(
      list(name = "Bullish Trend:", content = "When the SAR points are below the price, it signals that the asset is in an uptrend. Traders might consider holding long positions."),
      list(name = "Bearish Trend:", content = " When the SAR points are above the price, it indicates that the asset is in a downtrend. Traders might consider holding short positions.")
    )
  ),
  list(
    header = "Reversal Signals:",
    bullets = c("A reversal occurs when the price crosses the SAR indicator.",
                "This can signal a potential change in trend, prompting traders to exit their positions or enter new ones."),
    subpoints = NULL
  ),
  list(
    header = "Trailing Stop-Loss:",
    bullets = c("Traders often use the SAR as a trailing stop-loss mechanism.",
                "As the trend progresses, the SAR moves closer to the price, allowing traders to lock in profits while giving the trade room to run."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "The SAR is a lagging indicator, meaning it reacts to price movements after they happen. This may lead to missed opportunities if the market moves quickly."),
      list(name = "False Signals:", content = "In choppy or sideways markets, the SAR may generate false signals, as price may fluctuate frequently around the SAR points without establishing a clear trend.")
    )
  )
)


KST_info <- list(
  list(
    header = "Purpose:",
    bullets = c("The KST indicator helps traders identify potential buy and sell signals by analyzing momentum. It can indicate the strength of a trend and potential reversals."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("The KST line is generated by summing the weighted values of these ROCs, often smoothed again with a moving average.",
                "KST is calculated using four different rate-of-change (ROC) components, each smoothed by a moving average. The four components are typically calculated over different time frames:"),
    subpoints = list(
      list(name = "ROC1:", content = "Short-term (e.g., 10 days)"),
      list(name = "ROC2:", content = "Medium-term (e.g., 15 days)"),
      list(name = "ROC3:", content = "Longer-term (e.g., 20 days)"),
      list(name = "ROC4:", content = "Longest-term (e.g., 30 days)")
    )
  ),
  list(
    header = "Buy and Sell Signals:",
    bullets = NULL,
    subpoints = list(
      list(name = "Buy Signal:", content = "When the KST line crosses above the zero line or the signal line, it can indicate a bullish trend or momentum shift, suggesting a potential buy opportunity."),
      list(name = "Sell Signal:", content = "Conversely, when the KST line crosses below the zero line or the signal line, it may signal a bearish trend, suggesting a potential sell opportunity.")
    )
  ),
  list(
    header = "Trend Strength:",
    bullets = c("The distance between the KST line and the zero line can indicate the strength of the trend. A significant distance suggests strong momentum, while a line close to zero indicates weak momentum."),
    subpoints = NULL
  ),
  list(
    header = "Divergence:",
    bullets = c("Divergence between the KST line and the price can signal potential trend reversals.",
                "For example, if prices are making new highs while the KST is making lower highs, it may indicate weakening momentum."),
    subpoints = NULL
  ),
  list(
    header = "Volatility Measurement:",
    bullets = c("While KST primarily measures momentum, sharp changes in the KST line can indicate changes in market volatility and help traders adjust their strategies accordingly."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "KST is based on historical price data, which means it may not react quickly to sudden price changes. This lag can sometimes result in missed trading opportunities."),
      list(name = "False Signals:", content = "Like many technical indicators, KST can produce false signals, especially in choppy or sideways markets. It's advisable to use it in conjunction with other indicators for better confirmation.")
    )
  )
)

EMA_info <- list(
  list(
    header = "Purpose:",
    bullets = c("The EMA helps traders identify the direction of the trend and potential entry or exit points. It's commonly used in conjunction with other indicators for trading strategies."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("The EMA is calculated using a formula that applies a weighting factor, allowing it to react more quickly to price changes. This makes it particularly useful in volatile markets."),
    subpoints = NULL
  ),
  list(
    header = "Trend Identification:",
    bullets = c("When the price is above the EMA, it suggests a bullish trend. Conversely, when the price is below the EMA, it indicates a bearish trend."),
    subpoints = NULL
  ),
  list(
    header = "Crossover Signals:",
    bullets = c("Traders often use EMA crossovers as signals. For example, if a shorter EMA (like the 20-day) crosses above a longer EMA (like the 50-day), it might indicate a buying opportunity. Conversely, a crossover below might indicate a selling opportunity."),
    subpoints = NULL
  ),
  list(
    header = "Support and Resistance:",
    bullets = c("EMAs can act as dynamic support or resistance levels. In an uptrend, the price may bounce off the EMA, while in a downtrend, it may find resistance at the EMA."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "The EMA is lagging, meaning it reacts to price changes after they happen, which can lead to missed opportunities."),
      list(name = "False Signals:", content = "In sideways markets, the EMA might generate false signals, so it's advisable to use it alongside other technical indicators for confirmation.")
    )
  )
)

DEMA_info <- list(
  list(
    header = "Purpose:",
    bullets = c("DEMA is designed to give traders an enhanced view of price trends while reducing the lag that comes with standard moving averages. It can help identify potential buy and sell signals more effectively."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("DEMA is calculated using both the EMA and its own EMA. The formula involves a combination of a single EMA and an additional EMA of that EMA, allowing it to react more quickly to recent price changes."),
    subpoints = NULL
  ),
  list(
    header = "Trend Identification:",
    bullets = c("Similar to other moving averages, when the price is above the DEMA, it indicates an upward trend; when below, it suggests a downward trend."),
    subpoints = NULL
  ),
  list(
    header = "Crossover Signals:",
    bullets = c("DEMA can be used in conjunction with other moving averages (like EMA or SMA) to identify crossover signals. For example, if a shorter DEMA crosses above a longer one, it may indicate a bullish signal, while a crossover below could signal a bearish trend."),
    subpoints = NULL
  ),
  list(
    header = "Sensitivity to Price Changes:",
    bullets = c("DEMA is more sensitive to recent price movements than traditional EMAs, making it suitable for traders looking for quick signals in volatile markets."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "Although DEMA reduces lag compared to traditional moving averages, it still lags behind price movements to some extent. Traders should be aware of this when making decisions."),
      list(name = "False Signals:", content = "Like all moving averages, DEMA can generate false signals, especially in choppy or sideways markets. It's advisable to use it alongside other indicators for confirmation.")
    )
  )
)

MACD_CV_info <- list(
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "MACD Indicator",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Purpose:",
    bullets = c("MACD is primarily used to gauge the strength, direction, momentum, and duration of a trend in a stock's price. It's commonly utilized to identify potential reversals and continuations in the market."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("MACD is calculated by subtracting the 26-period EMA from the 12-period EMA. The result is the MACD line. A 9-period EMA of the MACD line is then plotted as the signal line.",
                "The difference between the MACD line and the signal line is often used to generate buy/sell signals."),
    subpoints = NULL
  ),
  list(
    header = "MACD Line and Signal Line:",
    bullets = c("The MACD line is typically more volatile and reacts quickly to price changes, while the signal line smooths out the MACD line."),
    subpoints = NULL
  ),
  list(
    header = "Crossover Signals:",
    bullets = c("A common trading signal occurs when the MACD line crosses above the signal line, suggesting a potential buying opportunity (bullish signal).",
                "Conversely, when the MACD line crosses below the signal line, it suggests a potential selling opportunity (bearish signal)."),
    subpoints = NULL
  ),
  list(
    header = "Histogram:",
    bullets = c("The histogram represents the difference between the MACD line and the signal line.",
                "A growing histogram indicates increasing momentum in the direction of the MACD line, while a shrinking histogram suggests decreasing momentum."),
    subpoints = NULL
  ),
  list(
    header = "Divergence:",
    bullets = c("Divergence between the MACD and the price can indicate potential reversals.",
                "For example, if prices are making new highs but the MACD is failing to do so, it could signal a weakening trend."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "MACD is a lagging indicator, meaning it reacts to past price movements. As a result, traders might miss some moves, especially in rapidly changing markets."),
      list(name = "False Signals:", content = "Like many indicators, MACD can produce false signals, particularly in sideways or choppy markets. Therefore, it's often best used in conjunction with other indicators or analysis techniques for confirmation.")
    )
  ),
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Chainkin Volatility",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "================================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Purpose:",
    bullets = c("To detect changes in market volatility before price movements.",
                "Helps in identifying potential breakout zones, trend reversals, and trend strength.",
                "Used to spot accumulation and distribution phases in the market."),
    subpoints = NULL
  ),
  list(
    header = "Breakout Confirmation:",
    bullets = c("Rising Chaikin Volatility indicates high volatility, which often precedes breakouts or large price moves.",
                "If the price is consolidating and volatility increases, expect a potential breakout."),
    subpoints = NULL
  ),
  list(
    header = "Trend Strength Analysis:",
    bullets = c("In uptrends, increasing volatility shows strong bullish momentum.",
                "In downtrends, rising volatility shows strong bearish pressure."),
    subpoints = NULL
  ),
  list(
    header = "Divergence Strategy:",
    bullets = c("If the price is making higher highs, but the volatility is decreasing, it signals a potential reversal."),
    subpoints = NULL
  ),
  list(
    header = "Limitations of Chaikin Volatility Indicator:",
    bullets = c("It does not indicate direction, only volatility.",
                "Can give false signals in choppy markets.",
                "Requires confirmation with other indicators like RSI, MACD, or Bollinger Bands.",
                "Does not work well in low-volume stocks or illiquid assets."),
    subpoints = NULL
  )
)

MACD_info <- list(
  list(
    header = "Purpose:",
    bullets = c("MACD is primarily used to gauge the strength, direction, momentum, and duration of a trend in a stock's price. It's commonly utilized to identify potential reversals and continuations in the market."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("MACD is calculated by subtracting the 26-period EMA from the 12-period EMA. The result is the MACD line. A 9-period EMA of the MACD line is then plotted as the signal line.",
                "The difference between the MACD line and the signal line is often used to generate buy/sell signals."),
    subpoints = NULL
  ),
  list(
    header = "MACD Line and Signal Line:",
    bullets = c("The MACD line is typically more volatile and reacts quickly to price changes, while the signal line smooths out the MACD line."),
    subpoints = NULL
  ),
  list(
    header = "Crossover Signals:",
    bullets = c("A common trading signal occurs when the MACD line crosses above the signal line, suggesting a potential buying opportunity (bullish signal).",
                "Conversely, when the MACD line crosses below the signal line, it suggests a potential selling opportunity (bearish signal)."),
    subpoints = NULL
  ),
  list(
    header = "Histogram:",
    bullets = c("The histogram represents the difference between the MACD line and the signal line.",
                "A growing histogram indicates increasing momentum in the direction of the MACD line, while a shrinking histogram suggests decreasing momentum."),
    subpoints = NULL
  ),
  list(
    header = "Divergence:",
    bullets = c("Divergence between the MACD and the price can indicate potential reversals.",
                "For example, if prices are making new highs but the MACD is failing to do so, it could signal a weakening trend."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "MACD is a lagging indicator, meaning it reacts to past price movements. As a result, traders might miss some moves, especially in rapidly changing markets."),
      list(name = "False Signals:", content = "Like many indicators, MACD can produce false signals, particularly in sideways or choppy markets. Therefore, it's often best used in conjunction with other indicators or analysis techniques for confirmation.")
    )
  )
)

BBands_info <- list(
  list(
    header = "Purpose:",
    bullets = c("Bollinger Bands are designed to indicate volatility and potential price reversals. They help traders identify periods of high or low volatility and potential entry and exit points."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("Bollinger Bands consist of three lines:"),
    subpoints = list(
      list(name = "Middle Band:", content = "This is typically a 20-period Simple Moving Average (SMA) of the price."),
      list(name = "Upper Band:", content = "This is the middle band plus two standard deviations of the price."),
      list(name = "Lower Band:", content = "This is the middle band minus two standard deviations of the price.")
    )
  ),
  list(
    header = "Trend Analysis:",
    bullets = c("When the price is above the upper band, it may indicate that the asset is overbought and could be due for a price correction.",
                "Conversely, when the price is below the lower band, it may signal that the asset is oversold and could rebound."),
    subpoints = NULL
  ),
  list(
    header = "Volatility Measurement:",
    bullets = c("The distance between the upper and lower bands reflects market volatility.",
                "A widening of the bands indicates increased volatility, while a narrowing suggests decreased volatility."),
    subpoints = NULL
  ),
  list(
    header = "Breakouts:",
    bullets = c("Prices breaking above or below the bands can signify strong momentum in the direction of the breakout.",
                "Traders may look for opportunities to enter trades following such breakouts."),
    subpoints = NULL
  ),
  list(
    header = "Bouncing off Bands:",
    bullets = c("Many traders use the bands as dynamic support and resistance levels.",
                "A price that touches or bounces off the lower band may be seen as a buying opportunity.",
                "while a price touching the upper band may be seen as a selling opportunity."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "As with many technical indicators, Bollinger Bands are based on historical prices and may lag current market movements."),
      list(name = "False Signals:", content = "Bollinger Bands can give false signals in volatile or sideways markets, where prices may frequently touch the bands without indicating a genuine trend.")
    )
  )
)


ATR_info <- list(
  list(
    header = "Purpose:",
    bullets = c("ATR is designed to quantify market volatility. It helps traders understand how much an asset typically moves over a specific period, which can inform their trading strategies, including setting stop-loss levels."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("The ATR is typically calculated as an exponential moving average (EMA) of the True Range over a specified period (commonly 14 days).",
                "The ATR is calculated based on the True Range (TR), which considers the greatest of the following:"),
    subpoints = list(
      list(name = "Current High minus Current Low", content = ""),
      list(name = "Current High minus Previous Close", content = ""),
      list(name = "Current Low minus Previous Close", content = "")
    )
  ),
  list(
    header = "Volatility Measurement:",
    bullets = c("ATR provides a numerical value representing the average range of price movements over the selected period.",
                "Higher ATR values indicate greater volatility, while lower values suggest less volatility."),
    subpoints = NULL
  ),
  list(
    header = "Setting Stop-Loss Orders:",
    bullets = c("Traders often use ATR to set stop-loss levels. A common method is to place a stop-loss order a certain multiple (e.g., 1.5 or 2 times the ATR) away from the entry price, allowing for normal market fluctuations while protecting against larger moves."),
    subpoints = NULL
  ),
  list(
    header = "Identifying Breakouts:",
    bullets = c("An increase in ATR may signal the potential for price breakouts.",
                "When ATR rises sharply, it indicates that price movements may become more significant, providing potential trading opportunities."),
    subpoints = NULL
  ),
  list(
    header = "Market Conditions:",
    bullets = c("Traders can gauge market conditions using ATR.",
                "A declining ATR may suggest a consolidating or quiet market.",
                "while a rising ATR indicates increasing volatility and potential trend changes."),
    subpoints = NULL
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "ATR is a lagging indicator based on past price data. As a result, it may not predict future movements but rather reflect current market conditions."),
      list(name = "No Directional Information:", content = "ATR does not provide information about the direction of price movement. It only measures volatility. Traders need to use other indicators to determine trend direction.")
    )
  )
)

ADX_info <- list(
  list(
    header = "Purpose:",
    bullets = c("The primary purpose of ADX is to measure the strength of a trend, not its direction.",
                "Identify when a market is trending strongly enough to justify entering a trade.",
                "Avoid trading in low-trending or sideways markets where the trend is weak or non-existent.",
                "Complement other trend-following indicators like Moving Averages or the Directional Movement Indicators (+DI and -DI)."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("The ADX is calculated using the relationship between the positive directional indicator (+DI) and the negative directional indicator (-DI):"),
    subpoints = list(
      list(name = "+DI measures the strength of upward movements.", content = ""),
      list(name = "-DI measures the strength of downward movements.", content = ""),
      list(name = "The ADX is derived by smoothing the Directional Movement Index (DMI), which compares the differences between the highs and lows over a period (typically 14 periods).", content = "")
    )
  ),
  list(
    header = "Strong Trend (ADX > 25):",
    bullets = c("A higher ADX indicates a strong trend in the market, whether it's an uptrend or a downtrend.",
                "Traders use this information to follow the prevailing trend, aiming to 'ride' the strength of the market move."),
    subpoints = NULL
  ),
  list(
    header = "Weak/No Trend (ADX < 20-25):",
    bullets = c("When the ADX is low, it implies a weak trend, often seen in range-bound or consolidating markets.",
                "Trend-following systems typically avoid trading during this time because the potential for profits is reduced."),
    subpoints = NULL
  ),
  list(
    header = "Divergence:",
    bullets = c("While the ADX itself does not give directional information (unlike MACD or RSI), divergence in the ADX indicator can still provide valuable insights:"),
    subpoints = list(
      list(name = "", content = "If price is making higher highs or lower lows but the ADX is declining, it suggests that the trend is losing strength, and a potential reversal or correction may be on the horizon."),
      list(name = "", content = "If price is moving sideways but ADX is rising, it indicates the market might be preparing to break out and enter a strong trend.")
    )
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "ADX, like most trend indicators, is a lagging indicator. It reflects past price action and requires time to smooth out the data. This means that the indicator will only confirm a trend after it has already begun."),
      list(name = "No Directional Information:", content = "ADX only shows the strength of the trend, not whether it's bullish or bearish. You need to use +DI and -DI or other indicators to determine the trend's direction."),
      list(name = "Whipsaw Risk:", content = "In choppy or volatile markets, ADX can give false signals. For example, ADX may rise above 25, suggesting a trend, but if the market quickly reverses or becomes erratic, this may lead to whipsaw trades (getting caught on both sides of a trade)."),
      list(name = "Not Useful for Range-Bound Markets:", content = "ADX is designed for trending markets, so it doesn't perform well during sideways, low-volatility phases. It could give false signals or unclear information in such scenarios.")
    )
  ),
  list(
    header = "Practical Use in Trading:",
    bullets = NULL,
    subpoints = list(
      list(name = "Combine with Directional Indicators:", content = "To get better signals, combine ADX with the directional movement lines (+DI and -DI). For example, when ADX > 25 and +DI is above -DI, it's a bullish signal; when -DI is above +DI, it's bearish."),
      list(name = "Exit Signals:", content = "ADX can also be useful for determining when to exit a trade. If ADX starts to fall below 25, it could signal a weakening trend, indicating that it may be time to book profits or exit the trade.")
    )
  )
)


CCI_info <- list(
  list(
    header = "Purpose:",
    bullets = c("The Commodity Channel Index (CCI) is designed to identify trends and potential reversals in price movements by comparing the current price to an average over a specified period.",
                "It is used primarily for spotting overbought and oversold conditions in the market, making it valuable for short-term traders.",
                "The CCI can also be employed in trend-following strategies when combined with other indicators."),
    subpoints = NULL
  ),
  list(
    header = "How it Works:",
    bullets = c("Commodity Channel Index to a stock chart, typically plotted as an oscillator fluctuating between positive and negative values.",
                "The CCI calculation uses the typical price (average of high, low, and close) and compares it to the moving average of the typical price."),
    subpoints = NULL
  ),
  list(
    header = "Overbought and Oversold Conditions:",
    bullets = NULL,
    subpoints = list(
      list(name = "CCI > 100:", content = "The asset is considered overbought, indicating it might be due for a price correction or pullback. This often serves as a sell signal."),
      list(name = "CCI < -100:", content = "The asset is considered oversold, suggesting that the price might rebound soon, and traders often interpret this as a buy signal.")
    )
  ),
  list(
    header = "Trend Reversals:",
    bullets = NULL,
    subpoints = list(
      list(name = "Positive CCI above 100:", content = "Suggest that the price is above its average, indicating a strong uptrend."),
      list(name = "Negative CCI below -100:", content = "Suggests that the price is below its average, indicating a downtrend.")
    )
  ),
  list(
    header = "Crossovers:",
    bullets = c("When the CCI moves above or below the 100 or -100 threshold, it is considered a potential indication of trend reversals or new emerging trends."),
    subpoints = NULL
  ),
  list(
    header = "Volatility Measurement:",
    bullets = c("While CCI is not specifically designed as a volatility indicator like Bollinger Bands or ATR, it does capture price volatility indirectly by measuring how far the current price deviates from the historical average.",
                "When the CCI values move far from zero (either positive or negative), it reflects increased volatility and a stronger deviation from the average."),
    subpoints = list(
      list(name = "High CCI readings:", content = "Indicate strong volatility, typically during sharp uptrends or downtrends. Conversely, values near zero suggest that price is close to its average, indicating low volatility or a sideways trend.")
    )
  ),
  list(
    header = "Limitations:",
    bullets = NULL,
    subpoints = list(
      list(name = "Lagging Indicator:", content = "CCI is a lagging indicator, meaning it uses historical data, which may delay recognizing a trend change. The signals might come after a significant portion of the move has already occurred, reducing the profitability of trades based on CCI alone."),
      list(name = "False Signals:", content = "CCI can sometimes produce false overbought or oversold signals during strong trending markets. For example, in a powerful uptrend, CCI might frequently indicate overbought conditions (CCI > 100), but the price continues to rise. Traders might exit early, missing further gains."),
      list(name = "Parameter Sensitivity:", content = "The effectiveness of CCI depends on the chosen period length (n). A shorter period (e.g., 10) makes the CCI more sensitive to price movements, generating more signals but also more noise. A longer period (e.g., 30) will smooth the data but may miss short-term opportunities."),
      list(name = "Doesn't Account for Price Magnitude:", content = "CCI only measures how far the price is from the average but doesn't take into account the magnitude of price changes. This means it might not be as useful in markets where the price fluctuates within narrow ranges or during low volatility periods."),
      list(name = "Not Effective in Non-Cyclical Markets:", content = "CCI is more effective in cyclical or volatile markets where price deviations from the mean occur frequently. It can be less useful in non-trending or choppy markets.")
    )
  )
)

Aroon_info <- list(
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Aroon Indicator",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Purpose:",
    bullets = c("The Aroon indicator is a technical analysis tool used to identify trends, the strength of a trend, and potential reversals in price movements.",
                "It consists of two lines: Aroon Up and Aroon Down, which measure the number of periods since the highest high and the lowest low over a specified number of periods."),
    subpoints = NULL
  ),
  list(
    header = "Interpretation of the Aroon Indicator:",
    bullets = NULL,
    subpoints = list(
      list(name = "Strong Uptrend:", content = "Aroon Up near 100 and Aroon Down near 0: Indicates a strong uptrend, where the stock price is frequently making new highs."),
      list(name = "Strong Downtrend:", content = "Aroon Down near 100 and Aroon Up near 0: Indicates a strong downtrend, where the stock price is frequently making new lows."),
      list(name = "Consolidation/Weak Trend:", content = "Both Aroon Up and Aroon Down are low (close to 0 or 50): This suggests a consolidation phase or a sideways market where neither new highs nor new lows are being made.")
    )
  ),
  list(
    header = "Trend Reversals:",
    bullets = NULL,
    subpoints = list(
      list(name = "Aroon Up crosses above Aroon Down:", content = "This could signal the start of a new uptrend."),
      list(name = "Aroon Down crosses above Aroon Up:", content = "This may indicate the start of a downtrend.")
    )
  ),
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Aroon Oscillator",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "================================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Purpose:",
    bullets = c("The Aroon Oscillator measures the difference between the Aroon Up and Aroon Down values. It oscillates between -100 and +100",
                "Positive values indicate that the market is in an uptrend.",
                "Negative values indicate that the market is in a downtrend.",
                "The higher the Aroon Oscillator value, the stronger the uptrend; the lower the value, the stronger the downtrend."),
    subpoints = NULL
  ),
  list(
    header = "Interpretation of Aroon Oscillator:",
    bullets = NULL,
    subpoints = list(
      list(name = "Strong Uptrend:", content = "When the Aroon Oscillator is above 50, it indicates a strong uptrend. The higher the value (closer to 100), the stronger the trend."),
      list(name = "Strong Downtrend:", content = "When the Aroon Oscillator is below -50, it signals a strong downtrend. The closer the value is to -100, the stronger the downward momentum.")
    )
  ),
  list(
    header = "Crossing the Zero Line:",
    bullets = NULL,
    subpoints = list(
      list(name = "Aroon Osc Above Zero:", content = "When the Aroon Oscillator crosses above zero, it suggests that a new uptrend might be starting."),
      list(name = "Aroon Osc Below Zero:", content = "When it crosses below zero, it signals a potential start of a downtrend.")
    )
  ),
  list(
    header = "Weak Trends or Consolidation:",
    bullets = c("When the Aroon Oscillator hovers around zero, it indicates a weak or non-existent trend, suggesting that the market is consolidating or moving sideways."),
    subpoints = NULL
  )
)

SMI_CMO_info <- list(
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Stochastic Momentum Index (SMI)",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Purpose:",
    bullets = c("The SMI aims to show the position of the current close relative to the midpoint of the high-low range over a given period.",
                "It provides more precise readings of momentum by incorporating smoothing factors, which help reduce noise and make the indicator more reliable in volatile markets.",
                "The SMI oscillates between -100 and +100."),
    subpoints = NULL
  ),
  list(
    header = "Overbought and Oversold Conditions:",
    bullets = NULL,
    subpoints = list(
      list(name = "Overbought:", content = "When the SMI is above +40 or +50, it indicates the asset may be overbought, suggesting a potential pullback or correction."),
      list(name = "Oversold:", content = "When the SMI is below -40 or -50, it suggests that the asset may be oversold, potentially signaling a buying opportunity or a reversal to the upside.")
    )
  ),
  list(
    header = "Trend Reversals:",
    bullets = NULL,
    subpoints = list(
      list(name = "SMI Crossovers:", content = "Traders look for crossovers of the SMI line with a signal line (typically a smoothed version of the SMI) to identify potential trend reversals."),
      list(name = "Bullish crossover:", content = "Occurs when the SMI line crosses above the signal line from below, indicating upward momentum."),
      list(name = "Bearish crossover:", content = "Occurs when the SMI line crosses below the signal line from above, signaling downward momentum."),
      list(name = "Zero Line Cross:", content = "When the SMI crosses the zero line, it can indicate a shift in momentum. A cross above zero suggests upward momentum, while a cross below zero indicates downward momentum.")
    )
  ),
  list(
    header = "===============================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Chande Momentum Oscillator (CMO)",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "================================================================================================================",
    bullets = NULL,
    subpoints = NULL
  ),
  list(
    header = "Purpose:",
    bullets = c("The Chande Momentum Oscillator shows whether a stock's price has experienced more positive or negative changes over a specified period. Like other momentum indicators, it can help identify trends, potential reversals, and overbought or oversold conditions.",
                "The CMO differs from the RSI in that it considers both upward and downward price changes directly, instead of just focusing on the relative magnitude of gains versus losses. This makes the CMO more responsive to short-term market fluctuations."),
    subpoints = NULL
  ),
  list(
    header = "Overbought and Oversold Conditions:",
    bullets = NULL,
    subpoints = list(
      list(name = "Overbought:", content = "When the CMO is above +50, it suggests that the stock may be overbought, meaning that it could be overvalued and due for a pullback or reversal."),
      list(name = "Oversold:", content = "When the CMO is below -50, it suggests that the stock may be oversold, meaning it could be undervalued and potentially ready for a bounce or reversal to the upside.")
    )
  ),
  list(
    header = "Trend Identification:",
    bullets = NULL,
    subpoints = list(
      list(name = "Rising CMO:", content = "A rising CMO indicates strengthening upward momentum. If the CMO is positive and increasing, it suggests that the stock is in an uptrend."),
      list(name = "Falling CMO:", content = "A falling CMO indicates weakening momentum or increasing downward pressure. If the CMO is negative and decreasing, it suggests that the stock is in a downtrend.")
    )
  ),
  list(
    header = "Crossing the Zero Line:",
    bullets = NULL,
    subpoints = list(
      list(name = "CMO Above Zero:", content = "When the CMO crosses above zero, it indicates that the momentum has shifted to the upside, signaling potential buying pressure."),
      list(name = "CMO Below Zero:", content = "When the CMO crosses below zero, it indicates that the momentum has shifted to the downside, signaling potential selling pressure.")
    )
  )
)


#' info
#'
#' @description A utils function
#'
#' @return The return value, if any, from executing the utility.
#'
#' @noRd
show_info_modal <- function(points, ind_title) {
  modalDialog(
    title = ind_title,
    easyClose = TRUE,
    size = "l",
    # Constructing the list of bullet points with sub-bullets
    tags$ul(
      lapply(points, function(point) {
        tags$li(
          strong(point$header),  # Bold header
          # Check if bullet points exist
          if (!is.null(point$bullets)) {
            tags$ul(
              lapply(point$bullets, function(bullet) {
                tags$li(bullet)  # Bullet point under the main header
              })
            )
          },
          # Check if subpoints exist
          if (!is.null(point$subpoints)) {
            tags$ul(
              lapply(point$subpoints, function(subpoint) {
                tags$li(strong(subpoint$name), subpoint$content)  # Bold sub-point name, normal text after
              })
            )
          } else {
            NULL  # No subpoints for this header
          }
        )
      })
    ),
    footer = modalButton("Close")  # Close button for the modal
  )
}
